---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

provisioner:
  name: chef_zero
  github: "opscode/chef"
  branch: <%= %x(git rev-parse HEAD) %>
  require_chef_omnibus: true
  data_path: test/fixtures

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-13.04
  - name: centos-6.4
  - name: centos-5.9

suites:
  - name: webapp
    run_list:
      - recipe[apt::default]
      - recipe[webapp::default]
    attributes:
