---
provisioner:
  name: chef_solo
  github: "opscode/chef"
  branch: "tball/yajl-replace-json" # TODO replace this when going to master
  require_chef_omnibus: true
  data_path: test/fixtures

platforms:
  - name: ubuntu-12.04
    driver_plugin: vagrant

suites:
  - name: webapp
    run_list:
      - recipe[apt::default]
      - recipe[webapp::default]
    attributes:
